version: "3.3"

services:
  app:
    image: appchat-docker/node:v1
    container_name: node_server
    env_file: .env
    environment:
      - BACKEND_PORT=5000
      - ACCESS_TOKEN=QUANLYTREEMACCESSTOKEN
      - REFRESH_TOKEN=QUANLYTREEMREFRESHTOKEN
      - ACCESS_TOKEN_LIFETIME=360000000000
      - REFRESH_TOKEN_LIFETIME=1y
      - DB_HOST_LOCAL=mongo
    volumes:
      - app:/home/haisang/AppChat/backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - common
  mongo:
    image: mongo
    container_name: mongodb
    env_file: .env
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mongodb+srv
      - DB_USER=haisang
      - DB_PASSWORD=123456abcxyz
      - DB_HOST=cluster0.nsh7c.mongodb.net
      - DB_PORT=27017
      - DB_NAME=AppChat
    volumes:
      - mongo:/var/lib/mongodb
    ports:
      - 27018:27017
    networks:
      - common
networks:
  common:
volumes:
  app:
  mongo:
